### PR TITLE
add peerDependency support for react 17

### PR DESCRIPTION
**Pull request by mrkan-alelgn**

### CODE REVIEW

**Comment by mrkan-alelgn** [comment]
react-container-query is firing peerDependency conflict error during npm install in react 17

**Comment by delagroove** [comment]
can you please push this one?

**Comment by akhilpanchal** [comment]
Hello @pixelbandito 
Is this project being maintained? I'll be happy to look into this and send a PR.

**Comment by jroru** [comment]
Anything blocking this being released? React 17 is widely used

**Comment by pixelbandito** [comment]
Ugh, I haven't been paying attention to this project for a while.
This looks good to me. Thanks for your efforts and persistence.

**Comment by jroru** [comment]
Thanks very much! What is the release process for this package?

**Comment by pixelbandito** [comment]
I'm going to merge some Dependabot-initiated minor version bumps and publish in the next couple of days.

**Pull request merged**
